### ISSUE TITLE
Missing comma causes dataset crash

### ISSUE THREAD

**Issue by bazylip** [bcmi/Image-Composition-Assessment-Dataset-CADB#2]
Missing comma in [line 28 of config](https://github.com/bcmi/Image-Composition-Assessment-Dataset-CADB/blob/2bfbc07d400276031e6ceab4aea2632783be7c9a/SAMPNet/config.py#L28) causes dataset to raise `KeyError`. Adding comma at the end of the line solves the issue. Full traceback:

```
$ python train.py 
Experiment name resnet18_samp_aaff_wemd4 

Create experiment directory:  (path)/samp-code/SAMPNet/./experiments/resnet18_samp_aaff_wemd4
Backup  test.py
Backup  train.py
Backup  cadb_dataset.py
Backup  samp_net.py
Backup  samp_module.py
Backup  config.py
Saliency-aware Multi-Pattern Pooling pattern: [1, 2, 3, 4, 5, 6, 7, 8], fusion manner: sum, dropout: 0.5
Create tensorboardX writer... (path)/samp-code/SAMPNet/./experiments/resnet18_samp_aaff_wemd4/logs
Traceback (most recent call last):
  File "train.py", line 258, in <module>
    trainer.run()
  File "train.py", line 99, in run
    self.run_epoch()
  File "train.py", line 168, in run_epoch
    for batch, data in enumerate(self.trainloader):
  File "(path)/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "(path)/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "(path)/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "(path)/venv/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "(path)/venv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "(path)/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "(path)/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "(path)/samp-code/SAMPNet/cadb_dataset.py", line 91, in __getitem__
    attrs = torch.tensor(self.get_attribute(image_name))
  File "(path)/samp-code/SAMPNet/cadb_dataset.py", line 104, in get_attribute
    attrs = [all_attrs[k] for k in self.attr_types]
  File "(path)/samp-code/SAMPNet/cadb_dataset.py", line 104, in <listcomp>
    attrs = [all_attrs[k] for k in self.attr_types]
KeyError: 'DoFObject'
```

**Comment by bo-zhang-cs** [comment]
Thanks for reminding, and I have fixed it.
